name = "Spect's modpack"
author = "ChiIdPuncher, CanInBad"
version = "A5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "642b94705b42c450ca43c6fa79619a94f9a2a1008aca7d15c9d059bbea5592ee"

[versions]
forge = "43.2.23"
minecraft = "1.19.2"
