name = "Spect's modpack"
author = "ChiIdPuncher, CanInBad"
version = "R1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4a5ece1254cbcd00de39d34862768ab255c0fb7bcf1994779756b3de968f37d"

[versions]
forge = "43.2.23"
minecraft = "1.19.2"
