name = "Spect's modpack"
author = "ChiIdPuncher, CanInBad"
version = "R2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "935356dca56b467094ac4dfd0ec023448f8e994d4e9376c1463480e1657f91ef"

[versions]
forge = "43.2.23"
minecraft = "1.19.2"
