name = "Spect's modpack"
author = "ChiIdPuncher, CanInBad"
version = "A3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e41ae69d5604e3109991dc84f8acf8d80a0ede89b09f6e99049eca44d7ed52c1"

[versions]
forge = "43.2.23"
minecraft = "1.19.2"
