name = "Spect's modpack"
author = "ChiIdPuncher, CanInBad"
version = "A4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2809959bc0757a6a23e937847aac84c093d3c043b1fdf7e9aa6df2f174f1b127"

[versions]
forge = "43.2.23"
minecraft = "1.19.2"
