name = "Spect's modpack"
author = "ChiIdPuncher, CanInBad"
version = "A3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75e926ac6664a3c6727cf308bc3e0b3cfe3f216e90c9fa453c6a94ddcebc32f4"

[versions]
forge = "43.2.23"
minecraft = "1.19.2"
