name = "Spect's modpack"
author = "ChiIdPuncher, CanInBad"
version = "A7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd9628211cb9dc83105365ad46b4b1c66c341d5ea2ecf8c567ea0fcedc15c334"

[versions]
forge = "43.2.23"
minecraft = "1.19.2"
