name = "happy lala funland 2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a614cfc4a780a4453f2c54c65dbbc131f58bac7e7cd43f4ba5600b1a3797515c"

[versions]
forge = "43.2.23"
minecraft = "1.19.2"
