name = "Spect's modpack"
author = "ChiIdPuncher, CanInBad"
version = "A7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "991aa649d353abbf6a50cff56b26852b4c5633b2bddb5ae5db4475ff2a9801c3"

[versions]
forge = "43.2.23"
minecraft = "1.19.2"
